// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/ll/v1/messages.proto

package llv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNSPECIFIED HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING_STATUS_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_SERVING_STATUS_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_carabiner_ll_v1_messages_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_carabiner_ll_v1_messages_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{26, 0}
}

// CheckRequest is the request for the Check RPC.
type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuple         *RelationTuple         `protobuf:"bytes,1,opt,name=tuple,proto3" json:"tuple,omitempty"`
	Consistency   *Consistency           `protobuf:"bytes,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetTuple() *RelationTuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

func (x *CheckRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

// CheckResponse is the response for the Check RPC.
type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	CheckedAt     *ConsistencyToken      `protobuf:"bytes,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetCheckedAt() *ConsistencyToken {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

// WriteRequest is the request for the Write RPC.
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writes        []*RelationTuple       `protobuf:"bytes,1,rep,name=writes,proto3" json:"writes,omitempty"`
	Deletes       []*RelationTuple       `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetWrites() []*RelationTuple {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *WriteRequest) GetDeletes() []*RelationTuple {
	if x != nil {
		return x.Deletes
	}
	return nil
}

// WriteResponse is the response for the Write RPC.
type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrittenAt     *ConsistencyToken      `protobuf:"bytes,1,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetWrittenAt() *ConsistencyToken {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

// ReadRequest is the request for the Read RPC.
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *RelationTupleFilter   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Consistency   *Consistency           `protobuf:"bytes,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetFilter() *RelationTupleFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *ReadRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReadRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ReadResponse is the response for the Read RPC.
type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuples        []*RelationTuple       `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetTuples() []*RelationTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

func (x *ReadResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// DeleteRequest is the request for the Delete RPC.
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *RelationTupleFilter   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetFilter() *RelationTupleFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// DeleteResponse is the response for the Delete RPC.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedAt     *ConsistencyToken      `protobuf:"bytes,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetDeletedAt() *ConsistencyToken {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// ListObjectsRequest is the request for the ListObjects RPC.
type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectType   string                 `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	ObjectType    string                 `protobuf:"bytes,4,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	Consistency   *Consistency           `protobuf:"bytes,5,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ListObjectsRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *ListObjectsRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ListObjectsRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *ListObjectsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ListObjectsRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

// ListObjectsResponse is the response for the ListObjects RPC.
type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectIds     []string               `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ListObjectsResponse) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

// ExpandRequest is the request for the Expand RPC.
type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	Consistency   *Consistency           `protobuf:"bytes,4,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ExpandRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ExpandRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ExpandRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *ExpandRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

// ExpandResponse is the response for the Expand RPC.
type ExpandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          *ExpandTree            `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ExpandResponse) GetTree() *ExpandTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

// ExpandTree represents the expansion of a permission.
type ExpandTree struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The relation or permission being expanded.
	Expanded string `protobuf:"bytes,1,opt,name=expanded,proto3" json:"expanded,omitempty"`
	// Types that are valid to be assigned to Node:
	//
	//	*ExpandTree_Leaf
	//	*ExpandTree_Union
	//	*ExpandTree_Intersection
	//	*ExpandTree_Exclusion
	Node          isExpandTree_Node `protobuf_oneof:"node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandTree) Reset() {
	*x = ExpandTree{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandTree) ProtoMessage() {}

func (x *ExpandTree) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandTree.ProtoReflect.Descriptor instead.
func (*ExpandTree) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ExpandTree) GetExpanded() string {
	if x != nil {
		return x.Expanded
	}
	return ""
}

func (x *ExpandTree) GetNode() isExpandTree_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ExpandTree) GetLeaf() *ExpandLeaf {
	if x != nil {
		if x, ok := x.Node.(*ExpandTree_Leaf); ok {
			return x.Leaf
		}
	}
	return nil
}

func (x *ExpandTree) GetUnion() *ExpandUnion {
	if x != nil {
		if x, ok := x.Node.(*ExpandTree_Union); ok {
			return x.Union
		}
	}
	return nil
}

func (x *ExpandTree) GetIntersection() *ExpandIntersection {
	if x != nil {
		if x, ok := x.Node.(*ExpandTree_Intersection); ok {
			return x.Intersection
		}
	}
	return nil
}

func (x *ExpandTree) GetExclusion() *ExpandExclusion {
	if x != nil {
		if x, ok := x.Node.(*ExpandTree_Exclusion); ok {
			return x.Exclusion
		}
	}
	return nil
}

type isExpandTree_Node interface {
	isExpandTree_Node()
}

type ExpandTree_Leaf struct {
	Leaf *ExpandLeaf `protobuf:"bytes,2,opt,name=leaf,proto3,oneof"`
}

type ExpandTree_Union struct {
	Union *ExpandUnion `protobuf:"bytes,3,opt,name=union,proto3,oneof"`
}

type ExpandTree_Intersection struct {
	Intersection *ExpandIntersection `protobuf:"bytes,4,opt,name=intersection,proto3,oneof"`
}

type ExpandTree_Exclusion struct {
	Exclusion *ExpandExclusion `protobuf:"bytes,5,opt,name=exclusion,proto3,oneof"`
}

func (*ExpandTree_Leaf) isExpandTree_Node() {}

func (*ExpandTree_Union) isExpandTree_Node() {}

func (*ExpandTree_Intersection) isExpandTree_Node() {}

func (*ExpandTree_Exclusion) isExpandTree_Node() {}

// ExpandLeaf contains the direct subjects.
type ExpandLeaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      []*RelationTuple       `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandLeaf) Reset() {
	*x = ExpandLeaf{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandLeaf) ProtoMessage() {}

func (x *ExpandLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandLeaf.ProtoReflect.Descriptor instead.
func (*ExpandLeaf) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *ExpandLeaf) GetSubjects() []*RelationTuple {
	if x != nil {
		return x.Subjects
	}
	return nil
}

// ExpandUnion combines children with OR logic.
type ExpandUnion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*ExpandTree          `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandUnion) Reset() {
	*x = ExpandUnion{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandUnion) ProtoMessage() {}

func (x *ExpandUnion) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandUnion.ProtoReflect.Descriptor instead.
func (*ExpandUnion) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ExpandUnion) GetChildren() []*ExpandTree {
	if x != nil {
		return x.Children
	}
	return nil
}

// ExpandIntersection combines children with AND logic.
type ExpandIntersection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*ExpandTree          `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandIntersection) Reset() {
	*x = ExpandIntersection{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandIntersection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandIntersection) ProtoMessage() {}

func (x *ExpandIntersection) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandIntersection.ProtoReflect.Descriptor instead.
func (*ExpandIntersection) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ExpandIntersection) GetChildren() []*ExpandTree {
	if x != nil {
		return x.Children
	}
	return nil
}

// ExpandExclusion subtracts one set from another.
type ExpandExclusion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *ExpandTree            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Subtract      *ExpandTree            `protobuf:"bytes,2,opt,name=subtract,proto3" json:"subtract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandExclusion) Reset() {
	*x = ExpandExclusion{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandExclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandExclusion) ProtoMessage() {}

func (x *ExpandExclusion) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandExclusion.ProtoReflect.Descriptor instead.
func (*ExpandExclusion) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *ExpandExclusion) GetBase() *ExpandTree {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ExpandExclusion) GetSubtract() *ExpandTree {
	if x != nil {
		return x.Subtract
	}
	return nil
}

// WriteSchemaRequest is the request for the WriteSchema RPC.
type WriteSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaYaml    string                 `protobuf:"bytes,1,opt,name=schema_yaml,json=schemaYaml,proto3" json:"schema_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSchemaRequest) Reset() {
	*x = WriteSchemaRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSchemaRequest) ProtoMessage() {}

func (x *WriteSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSchemaRequest.ProtoReflect.Descriptor instead.
func (*WriteSchemaRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *WriteSchemaRequest) GetSchemaYaml() string {
	if x != nil {
		return x.SchemaYaml
	}
	return ""
}

// WriteSchemaResponse is the response for the WriteSchema RPC.
type WriteSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSchemaResponse) Reset() {
	*x = WriteSchemaResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSchemaResponse) ProtoMessage() {}

func (x *WriteSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSchemaResponse.ProtoReflect.Descriptor instead.
func (*WriteSchemaResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{18}
}

// ReadSchemaRequest is the request for the ReadSchema RPC.
type ReadSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: if specified, returns only this named schema set.
	// If empty, returns all schema sets concatenated.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSchemaRequest) Reset() {
	*x = ReadSchemaRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSchemaRequest) ProtoMessage() {}

func (x *ReadSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSchemaRequest.ProtoReflect.Descriptor instead.
func (*ReadSchemaRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ReadSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ReadSchemaResponse is the response for the ReadSchema RPC.
type ReadSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaYaml    string                 `protobuf:"bytes,1,opt,name=schema_yaml,json=schemaYaml,proto3" json:"schema_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSchemaResponse) Reset() {
	*x = ReadSchemaResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSchemaResponse) ProtoMessage() {}

func (x *ReadSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSchemaResponse.ProtoReflect.Descriptor instead.
func (*ReadSchemaResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *ReadSchemaResponse) GetSchemaYaml() string {
	if x != nil {
		return x.SchemaYaml
	}
	return ""
}

// ListSchemaSetsRequest is the request for the ListSchemaSets RPC.
type ListSchemaSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemaSetsRequest) Reset() {
	*x = ListSchemaSetsRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemaSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemaSetsRequest) ProtoMessage() {}

func (x *ListSchemaSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemaSetsRequest.ProtoReflect.Descriptor instead.
func (*ListSchemaSetsRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{21}
}

// ListSchemaSetsResponse is the response for the ListSchemaSets RPC.
type ListSchemaSetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemaSetsResponse) Reset() {
	*x = ListSchemaSetsResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemaSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemaSetsResponse) ProtoMessage() {}

func (x *ListSchemaSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemaSetsResponse.ProtoReflect.Descriptor instead.
func (*ListSchemaSetsResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *ListSchemaSetsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// DeleteSchemaSetRequest is the request for the DeleteSchemaSet RPC.
type DeleteSchemaSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemaSetRequest) Reset() {
	*x = DeleteSchemaSetRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemaSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemaSetRequest) ProtoMessage() {}

func (x *DeleteSchemaSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemaSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSchemaSetRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteSchemaSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteSchemaSetResponse is the response for the DeleteSchemaSet RPC.
type DeleteSchemaSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemaSetResponse) Reset() {
	*x = DeleteSchemaSetResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemaSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemaSetResponse) ProtoMessage() {}

func (x *DeleteSchemaSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemaSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSchemaSetResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{24}
}

// HealthCheckRequest is the request for the HealthCheck RPC.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{25}
}

// HealthCheckResponse is the response for the HealthCheck RPC.
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=carabiner.ll.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{26}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNSPECIFIED
}

// WhoAmIRequest is the request for the WhoAmI RPC.
type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{27}
}

// WhoAmIResponse is the response for the WhoAmI RPC.
type WhoAmIResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authenticated subject (from JWT sub claim).
	// Empty if not authenticated.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Whether authentication is enabled on the server.
	Authenticated bool `protobuf:"varint,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// The user's IAM grants on Lamplight operations.
	Grants        []*IAMGrant `protobuf:"bytes,3,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{28}
}

func (x *WhoAmIResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *WhoAmIResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *WhoAmIResponse) GetGrants() []*IAMGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

// IAMGrant represents an IAM permission grant.
type IAMGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The object the grant applies to (e.g., "_lamplight.tuple:global" or "_lamplight.tuple:folder%3Amy-folder").
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// The relation granted (e.g., "writer", "reader", "executor").
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	// Human-readable description of what this grant allows.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IAMGrant) Reset() {
	*x = IAMGrant{}
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IAMGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IAMGrant) ProtoMessage() {}

func (x *IAMGrant) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IAMGrant.ProtoReflect.Descriptor instead.
func (*IAMGrant) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_messages_proto_rawDescGZIP(), []int{29}
}

func (x *IAMGrant) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *IAMGrant) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *IAMGrant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_carabiner_ll_v1_messages_proto protoreflect.FileDescriptor

const file_carabiner_ll_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1ecarabiner/ll/v1/messages.proto\x12\x0fcarabiner.ll.v1\x1a\x1bcarabiner/ll/v1/types.proto\"\x84\x01\n" +
	"\fCheckRequest\x124\n" +
	"\x05tuple\x18\x01 \x01(\v2\x1e.carabiner.ll.v1.RelationTupleR\x05tuple\x12>\n" +
	"\vconsistency\x18\x02 \x01(\v2\x1c.carabiner.ll.v1.ConsistencyR\vconsistency\"k\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12@\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\v2!.carabiner.ll.v1.ConsistencyTokenR\tcheckedAt\"\x80\x01\n" +
	"\fWriteRequest\x126\n" +
	"\x06writes\x18\x01 \x03(\v2\x1e.carabiner.ll.v1.RelationTupleR\x06writes\x128\n" +
	"\adeletes\x18\x02 \x03(\v2\x1e.carabiner.ll.v1.RelationTupleR\adeletes\"Q\n" +
	"\rWriteResponse\x12@\n" +
	"\n" +
	"written_at\x18\x01 \x01(\v2!.carabiner.ll.v1.ConsistencyTokenR\twrittenAt\"\xc7\x01\n" +
	"\vReadRequest\x12<\n" +
	"\x06filter\x18\x01 \x01(\v2$.carabiner.ll.v1.RelationTupleFilterR\x06filter\x12>\n" +
	"\vconsistency\x18\x02 \x01(\v2\x1c.carabiner.ll.v1.ConsistencyR\vconsistency\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"n\n" +
	"\fReadResponse\x126\n" +
	"\x06tuples\x18\x01 \x03(\v2\x1e.carabiner.ll.v1.RelationTupleR\x06tuples\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"M\n" +
	"\rDeleteRequest\x12<\n" +
	"\x06filter\x18\x01 \x01(\v2$.carabiner.ll.v1.RelationTupleFilterR\x06filter\"R\n" +
	"\x0eDeleteResponse\x12@\n" +
	"\n" +
	"deleted_at\x18\x01 \x01(\v2!.carabiner.ll.v1.ConsistencyTokenR\tdeletedAt\"\xd7\x01\n" +
	"\x12ListObjectsRequest\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x12\x1f\n" +
	"\vobject_type\x18\x04 \x01(\tR\n" +
	"objectType\x12>\n" +
	"\vconsistency\x18\x05 \x01(\v2\x1c.carabiner.ll.v1.ConsistencyR\vconsistency\"4\n" +
	"\x13ListObjectsResponse\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\tR\tobjectIds\"\xad\x01\n" +
	"\rExpandRequest\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x12>\n" +
	"\vconsistency\x18\x04 \x01(\v2\x1c.carabiner.ll.v1.ConsistencyR\vconsistency\"A\n" +
	"\x0eExpandResponse\x12/\n" +
	"\x04tree\x18\x01 \x01(\v2\x1b.carabiner.ll.v1.ExpandTreeR\x04tree\"\xa6\x02\n" +
	"\n" +
	"ExpandTree\x12\x1a\n" +
	"\bexpanded\x18\x01 \x01(\tR\bexpanded\x121\n" +
	"\x04leaf\x18\x02 \x01(\v2\x1b.carabiner.ll.v1.ExpandLeafH\x00R\x04leaf\x124\n" +
	"\x05union\x18\x03 \x01(\v2\x1c.carabiner.ll.v1.ExpandUnionH\x00R\x05union\x12I\n" +
	"\fintersection\x18\x04 \x01(\v2#.carabiner.ll.v1.ExpandIntersectionH\x00R\fintersection\x12@\n" +
	"\texclusion\x18\x05 \x01(\v2 .carabiner.ll.v1.ExpandExclusionH\x00R\texclusionB\x06\n" +
	"\x04node\"H\n" +
	"\n" +
	"ExpandLeaf\x12:\n" +
	"\bsubjects\x18\x01 \x03(\v2\x1e.carabiner.ll.v1.RelationTupleR\bsubjects\"F\n" +
	"\vExpandUnion\x127\n" +
	"\bchildren\x18\x01 \x03(\v2\x1b.carabiner.ll.v1.ExpandTreeR\bchildren\"M\n" +
	"\x12ExpandIntersection\x127\n" +
	"\bchildren\x18\x01 \x03(\v2\x1b.carabiner.ll.v1.ExpandTreeR\bchildren\"{\n" +
	"\x0fExpandExclusion\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.carabiner.ll.v1.ExpandTreeR\x04base\x127\n" +
	"\bsubtract\x18\x02 \x01(\v2\x1b.carabiner.ll.v1.ExpandTreeR\bsubtract\"5\n" +
	"\x12WriteSchemaRequest\x12\x1f\n" +
	"\vschema_yaml\x18\x01 \x01(\tR\n" +
	"schemaYaml\"\x15\n" +
	"\x13WriteSchemaResponse\"'\n" +
	"\x11ReadSchemaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x12ReadSchemaResponse\x12\x1f\n" +
	"\vschema_yaml\x18\x01 \x01(\tR\n" +
	"schemaYaml\"\x17\n" +
	"\x15ListSchemaSetsRequest\".\n" +
	"\x16ListSchemaSetsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\",\n" +
	"\x16DeleteSchemaSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17DeleteSchemaSetResponse\"\x14\n" +
	"\x12HealthCheckRequest\"\xce\x01\n" +
	"\x13HealthCheckResponse\x12J\n" +
	"\x06status\x18\x01 \x01(\x0e22.carabiner.ll.v1.HealthCheckResponse.ServingStatusR\x06status\"k\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\"\x0f\n" +
	"\rWhoAmIRequest\"\x83\x01\n" +
	"\x0eWhoAmIResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12$\n" +
	"\rauthenticated\x18\x02 \x01(\bR\rauthenticated\x121\n" +
	"\x06grants\x18\x03 \x03(\v2\x19.carabiner.ll.v1.IAMGrantR\x06grants\"`\n" +
	"\bIAMGrant\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB6Z4github.com/carabiner-dev/ll/api/carabiner/ll/v1;llv1b\x06proto3"

var (
	file_carabiner_ll_v1_messages_proto_rawDescOnce sync.Once
	file_carabiner_ll_v1_messages_proto_rawDescData []byte
)

func file_carabiner_ll_v1_messages_proto_rawDescGZIP() []byte {
	file_carabiner_ll_v1_messages_proto_rawDescOnce.Do(func() {
		file_carabiner_ll_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_ll_v1_messages_proto_rawDesc), len(file_carabiner_ll_v1_messages_proto_rawDesc)))
	})
	return file_carabiner_ll_v1_messages_proto_rawDescData
}

var file_carabiner_ll_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_carabiner_ll_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_carabiner_ll_v1_messages_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: carabiner.ll.v1.HealthCheckResponse.ServingStatus
	(*CheckRequest)(nil),                   // 1: carabiner.ll.v1.CheckRequest
	(*CheckResponse)(nil),                  // 2: carabiner.ll.v1.CheckResponse
	(*WriteRequest)(nil),                   // 3: carabiner.ll.v1.WriteRequest
	(*WriteResponse)(nil),                  // 4: carabiner.ll.v1.WriteResponse
	(*ReadRequest)(nil),                    // 5: carabiner.ll.v1.ReadRequest
	(*ReadResponse)(nil),                   // 6: carabiner.ll.v1.ReadResponse
	(*DeleteRequest)(nil),                  // 7: carabiner.ll.v1.DeleteRequest
	(*DeleteResponse)(nil),                 // 8: carabiner.ll.v1.DeleteResponse
	(*ListObjectsRequest)(nil),             // 9: carabiner.ll.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil),            // 10: carabiner.ll.v1.ListObjectsResponse
	(*ExpandRequest)(nil),                  // 11: carabiner.ll.v1.ExpandRequest
	(*ExpandResponse)(nil),                 // 12: carabiner.ll.v1.ExpandResponse
	(*ExpandTree)(nil),                     // 13: carabiner.ll.v1.ExpandTree
	(*ExpandLeaf)(nil),                     // 14: carabiner.ll.v1.ExpandLeaf
	(*ExpandUnion)(nil),                    // 15: carabiner.ll.v1.ExpandUnion
	(*ExpandIntersection)(nil),             // 16: carabiner.ll.v1.ExpandIntersection
	(*ExpandExclusion)(nil),                // 17: carabiner.ll.v1.ExpandExclusion
	(*WriteSchemaRequest)(nil),             // 18: carabiner.ll.v1.WriteSchemaRequest
	(*WriteSchemaResponse)(nil),            // 19: carabiner.ll.v1.WriteSchemaResponse
	(*ReadSchemaRequest)(nil),              // 20: carabiner.ll.v1.ReadSchemaRequest
	(*ReadSchemaResponse)(nil),             // 21: carabiner.ll.v1.ReadSchemaResponse
	(*ListSchemaSetsRequest)(nil),          // 22: carabiner.ll.v1.ListSchemaSetsRequest
	(*ListSchemaSetsResponse)(nil),         // 23: carabiner.ll.v1.ListSchemaSetsResponse
	(*DeleteSchemaSetRequest)(nil),         // 24: carabiner.ll.v1.DeleteSchemaSetRequest
	(*DeleteSchemaSetResponse)(nil),        // 25: carabiner.ll.v1.DeleteSchemaSetResponse
	(*HealthCheckRequest)(nil),             // 26: carabiner.ll.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 27: carabiner.ll.v1.HealthCheckResponse
	(*WhoAmIRequest)(nil),                  // 28: carabiner.ll.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),                 // 29: carabiner.ll.v1.WhoAmIResponse
	(*IAMGrant)(nil),                       // 30: carabiner.ll.v1.IAMGrant
	(*RelationTuple)(nil),                  // 31: carabiner.ll.v1.RelationTuple
	(*Consistency)(nil),                    // 32: carabiner.ll.v1.Consistency
	(*ConsistencyToken)(nil),               // 33: carabiner.ll.v1.ConsistencyToken
	(*RelationTupleFilter)(nil),            // 34: carabiner.ll.v1.RelationTupleFilter
}
var file_carabiner_ll_v1_messages_proto_depIdxs = []int32{
	31, // 0: carabiner.ll.v1.CheckRequest.tuple:type_name -> carabiner.ll.v1.RelationTuple
	32, // 1: carabiner.ll.v1.CheckRequest.consistency:type_name -> carabiner.ll.v1.Consistency
	33, // 2: carabiner.ll.v1.CheckResponse.checked_at:type_name -> carabiner.ll.v1.ConsistencyToken
	31, // 3: carabiner.ll.v1.WriteRequest.writes:type_name -> carabiner.ll.v1.RelationTuple
	31, // 4: carabiner.ll.v1.WriteRequest.deletes:type_name -> carabiner.ll.v1.RelationTuple
	33, // 5: carabiner.ll.v1.WriteResponse.written_at:type_name -> carabiner.ll.v1.ConsistencyToken
	34, // 6: carabiner.ll.v1.ReadRequest.filter:type_name -> carabiner.ll.v1.RelationTupleFilter
	32, // 7: carabiner.ll.v1.ReadRequest.consistency:type_name -> carabiner.ll.v1.Consistency
	31, // 8: carabiner.ll.v1.ReadResponse.tuples:type_name -> carabiner.ll.v1.RelationTuple
	34, // 9: carabiner.ll.v1.DeleteRequest.filter:type_name -> carabiner.ll.v1.RelationTupleFilter
	33, // 10: carabiner.ll.v1.DeleteResponse.deleted_at:type_name -> carabiner.ll.v1.ConsistencyToken
	32, // 11: carabiner.ll.v1.ListObjectsRequest.consistency:type_name -> carabiner.ll.v1.Consistency
	32, // 12: carabiner.ll.v1.ExpandRequest.consistency:type_name -> carabiner.ll.v1.Consistency
	13, // 13: carabiner.ll.v1.ExpandResponse.tree:type_name -> carabiner.ll.v1.ExpandTree
	14, // 14: carabiner.ll.v1.ExpandTree.leaf:type_name -> carabiner.ll.v1.ExpandLeaf
	15, // 15: carabiner.ll.v1.ExpandTree.union:type_name -> carabiner.ll.v1.ExpandUnion
	16, // 16: carabiner.ll.v1.ExpandTree.intersection:type_name -> carabiner.ll.v1.ExpandIntersection
	17, // 17: carabiner.ll.v1.ExpandTree.exclusion:type_name -> carabiner.ll.v1.ExpandExclusion
	31, // 18: carabiner.ll.v1.ExpandLeaf.subjects:type_name -> carabiner.ll.v1.RelationTuple
	13, // 19: carabiner.ll.v1.ExpandUnion.children:type_name -> carabiner.ll.v1.ExpandTree
	13, // 20: carabiner.ll.v1.ExpandIntersection.children:type_name -> carabiner.ll.v1.ExpandTree
	13, // 21: carabiner.ll.v1.ExpandExclusion.base:type_name -> carabiner.ll.v1.ExpandTree
	13, // 22: carabiner.ll.v1.ExpandExclusion.subtract:type_name -> carabiner.ll.v1.ExpandTree
	0,  // 23: carabiner.ll.v1.HealthCheckResponse.status:type_name -> carabiner.ll.v1.HealthCheckResponse.ServingStatus
	30, // 24: carabiner.ll.v1.WhoAmIResponse.grants:type_name -> carabiner.ll.v1.IAMGrant
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_carabiner_ll_v1_messages_proto_init() }
func file_carabiner_ll_v1_messages_proto_init() {
	if File_carabiner_ll_v1_messages_proto != nil {
		return
	}
	file_carabiner_ll_v1_types_proto_init()
	file_carabiner_ll_v1_messages_proto_msgTypes[12].OneofWrappers = []any{
		(*ExpandTree_Leaf)(nil),
		(*ExpandTree_Union)(nil),
		(*ExpandTree_Intersection)(nil),
		(*ExpandTree_Exclusion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_ll_v1_messages_proto_rawDesc), len(file_carabiner_ll_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_ll_v1_messages_proto_goTypes,
		DependencyIndexes: file_carabiner_ll_v1_messages_proto_depIdxs,
		EnumInfos:         file_carabiner_ll_v1_messages_proto_enumTypes,
		MessageInfos:      file_carabiner_ll_v1_messages_proto_msgTypes,
	}.Build()
	File_carabiner_ll_v1_messages_proto = out.File
	file_carabiner_ll_v1_messages_proto_goTypes = nil
	file_carabiner_ll_v1_messages_proto_depIdxs = nil
}
