// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/ll/v1/service.proto

package llv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_carabiner_ll_v1_service_proto protoreflect.FileDescriptor

const file_carabiner_ll_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dcarabiner/ll/v1/service.proto\x12\x0fcarabiner.ll.v1\x1a\x1ecarabiner/ll/v1/messages.proto2\xf6\a\n" +
	"\x10LamplightService\x12F\n" +
	"\x05Check\x12\x1d.carabiner.ll.v1.CheckRequest\x1a\x1e.carabiner.ll.v1.CheckResponse\x12F\n" +
	"\x05Write\x12\x1d.carabiner.ll.v1.WriteRequest\x1a\x1e.carabiner.ll.v1.WriteResponse\x12C\n" +
	"\x04Read\x12\x1c.carabiner.ll.v1.ReadRequest\x1a\x1d.carabiner.ll.v1.ReadResponse\x12I\n" +
	"\x06Delete\x12\x1e.carabiner.ll.v1.DeleteRequest\x1a\x1f.carabiner.ll.v1.DeleteResponse\x12X\n" +
	"\vListObjects\x12#.carabiner.ll.v1.ListObjectsRequest\x1a$.carabiner.ll.v1.ListObjectsResponse\x12I\n" +
	"\x06Expand\x12\x1e.carabiner.ll.v1.ExpandRequest\x1a\x1f.carabiner.ll.v1.ExpandResponse\x12X\n" +
	"\vWriteSchema\x12#.carabiner.ll.v1.WriteSchemaRequest\x1a$.carabiner.ll.v1.WriteSchemaResponse\x12U\n" +
	"\n" +
	"ReadSchema\x12\".carabiner.ll.v1.ReadSchemaRequest\x1a#.carabiner.ll.v1.ReadSchemaResponse\x12a\n" +
	"\x0eListSchemaSets\x12&.carabiner.ll.v1.ListSchemaSetsRequest\x1a'.carabiner.ll.v1.ListSchemaSetsResponse\x12d\n" +
	"\x0fDeleteSchemaSet\x12'.carabiner.ll.v1.DeleteSchemaSetRequest\x1a(.carabiner.ll.v1.DeleteSchemaSetResponse\x12X\n" +
	"\vHealthCheck\x12#.carabiner.ll.v1.HealthCheckRequest\x1a$.carabiner.ll.v1.HealthCheckResponse\x12I\n" +
	"\x06WhoAmI\x12\x1e.carabiner.ll.v1.WhoAmIRequest\x1a\x1f.carabiner.ll.v1.WhoAmIResponseB6Z4github.com/carabiner-dev/ll/api/carabiner/ll/v1;llv1b\x06proto3"

var file_carabiner_ll_v1_service_proto_goTypes = []any{
	(*CheckRequest)(nil),            // 0: carabiner.ll.v1.CheckRequest
	(*WriteRequest)(nil),            // 1: carabiner.ll.v1.WriteRequest
	(*ReadRequest)(nil),             // 2: carabiner.ll.v1.ReadRequest
	(*DeleteRequest)(nil),           // 3: carabiner.ll.v1.DeleteRequest
	(*ListObjectsRequest)(nil),      // 4: carabiner.ll.v1.ListObjectsRequest
	(*ExpandRequest)(nil),           // 5: carabiner.ll.v1.ExpandRequest
	(*WriteSchemaRequest)(nil),      // 6: carabiner.ll.v1.WriteSchemaRequest
	(*ReadSchemaRequest)(nil),       // 7: carabiner.ll.v1.ReadSchemaRequest
	(*ListSchemaSetsRequest)(nil),   // 8: carabiner.ll.v1.ListSchemaSetsRequest
	(*DeleteSchemaSetRequest)(nil),  // 9: carabiner.ll.v1.DeleteSchemaSetRequest
	(*HealthCheckRequest)(nil),      // 10: carabiner.ll.v1.HealthCheckRequest
	(*WhoAmIRequest)(nil),           // 11: carabiner.ll.v1.WhoAmIRequest
	(*CheckResponse)(nil),           // 12: carabiner.ll.v1.CheckResponse
	(*WriteResponse)(nil),           // 13: carabiner.ll.v1.WriteResponse
	(*ReadResponse)(nil),            // 14: carabiner.ll.v1.ReadResponse
	(*DeleteResponse)(nil),          // 15: carabiner.ll.v1.DeleteResponse
	(*ListObjectsResponse)(nil),     // 16: carabiner.ll.v1.ListObjectsResponse
	(*ExpandResponse)(nil),          // 17: carabiner.ll.v1.ExpandResponse
	(*WriteSchemaResponse)(nil),     // 18: carabiner.ll.v1.WriteSchemaResponse
	(*ReadSchemaResponse)(nil),      // 19: carabiner.ll.v1.ReadSchemaResponse
	(*ListSchemaSetsResponse)(nil),  // 20: carabiner.ll.v1.ListSchemaSetsResponse
	(*DeleteSchemaSetResponse)(nil), // 21: carabiner.ll.v1.DeleteSchemaSetResponse
	(*HealthCheckResponse)(nil),     // 22: carabiner.ll.v1.HealthCheckResponse
	(*WhoAmIResponse)(nil),          // 23: carabiner.ll.v1.WhoAmIResponse
}
var file_carabiner_ll_v1_service_proto_depIdxs = []int32{
	0,  // 0: carabiner.ll.v1.LamplightService.Check:input_type -> carabiner.ll.v1.CheckRequest
	1,  // 1: carabiner.ll.v1.LamplightService.Write:input_type -> carabiner.ll.v1.WriteRequest
	2,  // 2: carabiner.ll.v1.LamplightService.Read:input_type -> carabiner.ll.v1.ReadRequest
	3,  // 3: carabiner.ll.v1.LamplightService.Delete:input_type -> carabiner.ll.v1.DeleteRequest
	4,  // 4: carabiner.ll.v1.LamplightService.ListObjects:input_type -> carabiner.ll.v1.ListObjectsRequest
	5,  // 5: carabiner.ll.v1.LamplightService.Expand:input_type -> carabiner.ll.v1.ExpandRequest
	6,  // 6: carabiner.ll.v1.LamplightService.WriteSchema:input_type -> carabiner.ll.v1.WriteSchemaRequest
	7,  // 7: carabiner.ll.v1.LamplightService.ReadSchema:input_type -> carabiner.ll.v1.ReadSchemaRequest
	8,  // 8: carabiner.ll.v1.LamplightService.ListSchemaSets:input_type -> carabiner.ll.v1.ListSchemaSetsRequest
	9,  // 9: carabiner.ll.v1.LamplightService.DeleteSchemaSet:input_type -> carabiner.ll.v1.DeleteSchemaSetRequest
	10, // 10: carabiner.ll.v1.LamplightService.HealthCheck:input_type -> carabiner.ll.v1.HealthCheckRequest
	11, // 11: carabiner.ll.v1.LamplightService.WhoAmI:input_type -> carabiner.ll.v1.WhoAmIRequest
	12, // 12: carabiner.ll.v1.LamplightService.Check:output_type -> carabiner.ll.v1.CheckResponse
	13, // 13: carabiner.ll.v1.LamplightService.Write:output_type -> carabiner.ll.v1.WriteResponse
	14, // 14: carabiner.ll.v1.LamplightService.Read:output_type -> carabiner.ll.v1.ReadResponse
	15, // 15: carabiner.ll.v1.LamplightService.Delete:output_type -> carabiner.ll.v1.DeleteResponse
	16, // 16: carabiner.ll.v1.LamplightService.ListObjects:output_type -> carabiner.ll.v1.ListObjectsResponse
	17, // 17: carabiner.ll.v1.LamplightService.Expand:output_type -> carabiner.ll.v1.ExpandResponse
	18, // 18: carabiner.ll.v1.LamplightService.WriteSchema:output_type -> carabiner.ll.v1.WriteSchemaResponse
	19, // 19: carabiner.ll.v1.LamplightService.ReadSchema:output_type -> carabiner.ll.v1.ReadSchemaResponse
	20, // 20: carabiner.ll.v1.LamplightService.ListSchemaSets:output_type -> carabiner.ll.v1.ListSchemaSetsResponse
	21, // 21: carabiner.ll.v1.LamplightService.DeleteSchemaSet:output_type -> carabiner.ll.v1.DeleteSchemaSetResponse
	22, // 22: carabiner.ll.v1.LamplightService.HealthCheck:output_type -> carabiner.ll.v1.HealthCheckResponse
	23, // 23: carabiner.ll.v1.LamplightService.WhoAmI:output_type -> carabiner.ll.v1.WhoAmIResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_carabiner_ll_v1_service_proto_init() }
func file_carabiner_ll_v1_service_proto_init() {
	if File_carabiner_ll_v1_service_proto != nil {
		return
	}
	file_carabiner_ll_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_ll_v1_service_proto_rawDesc), len(file_carabiner_ll_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carabiner_ll_v1_service_proto_goTypes,
		DependencyIndexes: file_carabiner_ll_v1_service_proto_depIdxs,
	}.Build()
	File_carabiner_ll_v1_service_proto = out.File
	file_carabiner_ll_v1_service_proto_goTypes = nil
	file_carabiner_ll_v1_service_proto_depIdxs = nil
}
