// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: carabiner/ll/v1/service.proto

package llv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LamplightService_Check_FullMethodName               = "/carabiner.ll.v1.LamplightService/Check"
	LamplightService_Write_FullMethodName               = "/carabiner.ll.v1.LamplightService/Write"
	LamplightService_Read_FullMethodName                = "/carabiner.ll.v1.LamplightService/Read"
	LamplightService_Delete_FullMethodName              = "/carabiner.ll.v1.LamplightService/Delete"
	LamplightService_ListObjects_FullMethodName         = "/carabiner.ll.v1.LamplightService/ListObjects"
	LamplightService_Expand_FullMethodName              = "/carabiner.ll.v1.LamplightService/Expand"
	LamplightService_WriteSchema_FullMethodName         = "/carabiner.ll.v1.LamplightService/WriteSchema"
	LamplightService_ReadSchema_FullMethodName          = "/carabiner.ll.v1.LamplightService/ReadSchema"
	LamplightService_ListSchemaSets_FullMethodName      = "/carabiner.ll.v1.LamplightService/ListSchemaSets"
	LamplightService_DeleteSchemaSet_FullMethodName     = "/carabiner.ll.v1.LamplightService/DeleteSchemaSet"
	LamplightService_HealthCheck_FullMethodName         = "/carabiner.ll.v1.LamplightService/HealthCheck"
	LamplightService_WhoAmI_FullMethodName              = "/carabiner.ll.v1.LamplightService/WhoAmI"
	LamplightService_EnsurePath_FullMethodName          = "/carabiner.ll.v1.LamplightService/EnsurePath"
	LamplightService_CheckPath_FullMethodName           = "/carabiner.ll.v1.LamplightService/CheckPath"
	LamplightService_GrantRole_FullMethodName           = "/carabiner.ll.v1.LamplightService/GrantRole"
	LamplightService_RevokeRole_FullMethodName          = "/carabiner.ll.v1.LamplightService/RevokeRole"
	LamplightService_ListRoleAssignments_FullMethodName = "/carabiner.ll.v1.LamplightService/ListRoleAssignments"
	LamplightService_ListRoles_FullMethodName           = "/carabiner.ll.v1.LamplightService/ListRoles"
)

// LamplightServiceClient is the client API for LamplightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LamplightService provides a Google Zanzibar-style permissions API.
type LamplightServiceClient interface {
	// Check determines whether a subject has a permission on an object.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// Write creates or touches relation tuples.
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// Read returns relation tuples matching a filter.
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Delete removes relation tuples matching a filter.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// ListObjects returns all objects of a given type on which the subject has a permission.
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	// Expand returns the full tree of subjects with a given permission on an object.
	Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error)
	// WriteSchema writes or updates a named schema set.
	WriteSchema(ctx context.Context, in *WriteSchemaRequest, opts ...grpc.CallOption) (*WriteSchemaResponse, error)
	// ReadSchema returns the authorization schema. If name is specified, returns that
	// specific schema set. Otherwise returns all schema sets concatenated.
	ReadSchema(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error)
	// ListSchemaSets returns the names of all stored schema sets.
	ListSchemaSets(ctx context.Context, in *ListSchemaSetsRequest, opts ...grpc.CallOption) (*ListSchemaSetsResponse, error)
	// DeleteSchemaSet removes a named schema set.
	DeleteSchemaSet(ctx context.Context, in *DeleteSchemaSetRequest, opts ...grpc.CallOption) (*DeleteSchemaSetResponse, error)
	// HealthCheck returns the health of the service.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// WhoAmI returns the authenticated user's identity and IAM grants.
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// EnsurePath ensures all parent tuples exist for a hierarchical path.
	// It parses the path, checks which tuples already exist, and creates only
	// the missing ones. Returns information about what was created vs. existed.
	//
	// Path format: type:id>type:id>type:id#relation
	// Example: folder:root>folder:projects>file:readme.md#parent
	//
	// This creates tuples connecting each child to its parent:
	//
	//	folder:projects#parent@folder:root
	//	file:readme.md#parent@folder:projects
	EnsurePath(ctx context.Context, in *EnsurePathRequest, opts ...grpc.CallOption) (*EnsurePathResponse, error)
	// CheckPath checks if all tuples in a hierarchical path exist.
	// It parses the path and checks each tuple without creating any.
	// Returns which tuples exist and which are missing.
	CheckPath(ctx context.Context, in *CheckPathRequest, opts ...grpc.CallOption) (*CheckPathResponse, error)
	// GrantRole assigns a role to a subject on an object.
	// Roles are defined in the server configuration and expand to a set of tuples.
	// Role-granted tuples cannot be deleted individually; they are removed when
	// the role is revoked.
	GrantRole(ctx context.Context, in *GrantRoleRequest, opts ...grpc.CallOption) (*GrantRoleResponse, error)
	// RevokeRole removes a role assignment from a subject on an object.
	// This deletes all tuples that were created when the role was granted.
	RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error)
	// ListRoleAssignments returns all role assignments matching the filter.
	ListRoleAssignments(ctx context.Context, in *ListRoleAssignmentsRequest, opts ...grpc.CallOption) (*ListRoleAssignmentsResponse, error)
	// ListRoles returns the names of all defined roles.
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
}

type lamplightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLamplightServiceClient(cc grpc.ClientConnInterface) LamplightServiceClient {
	return &lamplightServiceClient{cc}
}

func (c *lamplightServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, LamplightService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, LamplightService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, LamplightService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, LamplightService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, LamplightService_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpandResponse)
	err := c.cc.Invoke(ctx, LamplightService_Expand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) WriteSchema(ctx context.Context, in *WriteSchemaRequest, opts ...grpc.CallOption) (*WriteSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteSchemaResponse)
	err := c.cc.Invoke(ctx, LamplightService_WriteSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) ReadSchema(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSchemaResponse)
	err := c.cc.Invoke(ctx, LamplightService_ReadSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) ListSchemaSets(ctx context.Context, in *ListSchemaSetsRequest, opts ...grpc.CallOption) (*ListSchemaSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemaSetsResponse)
	err := c.cc.Invoke(ctx, LamplightService_ListSchemaSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) DeleteSchemaSet(ctx context.Context, in *DeleteSchemaSetRequest, opts ...grpc.CallOption) (*DeleteSchemaSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSchemaSetResponse)
	err := c.cc.Invoke(ctx, LamplightService_DeleteSchemaSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, LamplightService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, LamplightService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) EnsurePath(ctx context.Context, in *EnsurePathRequest, opts ...grpc.CallOption) (*EnsurePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsurePathResponse)
	err := c.cc.Invoke(ctx, LamplightService_EnsurePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) CheckPath(ctx context.Context, in *CheckPathRequest, opts ...grpc.CallOption) (*CheckPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPathResponse)
	err := c.cc.Invoke(ctx, LamplightService_CheckPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) GrantRole(ctx context.Context, in *GrantRoleRequest, opts ...grpc.CallOption) (*GrantRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantRoleResponse)
	err := c.cc.Invoke(ctx, LamplightService_GrantRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeRoleResponse)
	err := c.cc.Invoke(ctx, LamplightService_RevokeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) ListRoleAssignments(ctx context.Context, in *ListRoleAssignmentsRequest, opts ...grpc.CallOption) (*ListRoleAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleAssignmentsResponse)
	err := c.cc.Invoke(ctx, LamplightService_ListRoleAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lamplightServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, LamplightService_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LamplightServiceServer is the server API for LamplightService service.
// All implementations must embed UnimplementedLamplightServiceServer
// for forward compatibility.
//
// LamplightService provides a Google Zanzibar-style permissions API.
type LamplightServiceServer interface {
	// Check determines whether a subject has a permission on an object.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// Write creates or touches relation tuples.
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	// Read returns relation tuples matching a filter.
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// Delete removes relation tuples matching a filter.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// ListObjects returns all objects of a given type on which the subject has a permission.
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	// Expand returns the full tree of subjects with a given permission on an object.
	Expand(context.Context, *ExpandRequest) (*ExpandResponse, error)
	// WriteSchema writes or updates a named schema set.
	WriteSchema(context.Context, *WriteSchemaRequest) (*WriteSchemaResponse, error)
	// ReadSchema returns the authorization schema. If name is specified, returns that
	// specific schema set. Otherwise returns all schema sets concatenated.
	ReadSchema(context.Context, *ReadSchemaRequest) (*ReadSchemaResponse, error)
	// ListSchemaSets returns the names of all stored schema sets.
	ListSchemaSets(context.Context, *ListSchemaSetsRequest) (*ListSchemaSetsResponse, error)
	// DeleteSchemaSet removes a named schema set.
	DeleteSchemaSet(context.Context, *DeleteSchemaSetRequest) (*DeleteSchemaSetResponse, error)
	// HealthCheck returns the health of the service.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// WhoAmI returns the authenticated user's identity and IAM grants.
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	// EnsurePath ensures all parent tuples exist for a hierarchical path.
	// It parses the path, checks which tuples already exist, and creates only
	// the missing ones. Returns information about what was created vs. existed.
	//
	// Path format: type:id>type:id>type:id#relation
	// Example: folder:root>folder:projects>file:readme.md#parent
	//
	// This creates tuples connecting each child to its parent:
	//
	//	folder:projects#parent@folder:root
	//	file:readme.md#parent@folder:projects
	EnsurePath(context.Context, *EnsurePathRequest) (*EnsurePathResponse, error)
	// CheckPath checks if all tuples in a hierarchical path exist.
	// It parses the path and checks each tuple without creating any.
	// Returns which tuples exist and which are missing.
	CheckPath(context.Context, *CheckPathRequest) (*CheckPathResponse, error)
	// GrantRole assigns a role to a subject on an object.
	// Roles are defined in the server configuration and expand to a set of tuples.
	// Role-granted tuples cannot be deleted individually; they are removed when
	// the role is revoked.
	GrantRole(context.Context, *GrantRoleRequest) (*GrantRoleResponse, error)
	// RevokeRole removes a role assignment from a subject on an object.
	// This deletes all tuples that were created when the role was granted.
	RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error)
	// ListRoleAssignments returns all role assignments matching the filter.
	ListRoleAssignments(context.Context, *ListRoleAssignmentsRequest) (*ListRoleAssignmentsResponse, error)
	// ListRoles returns the names of all defined roles.
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	mustEmbedUnimplementedLamplightServiceServer()
}

// UnimplementedLamplightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLamplightServiceServer struct{}

func (UnimplementedLamplightServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedLamplightServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedLamplightServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedLamplightServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLamplightServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedLamplightServiceServer) Expand(context.Context, *ExpandRequest) (*ExpandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Expand not implemented")
}
func (UnimplementedLamplightServiceServer) WriteSchema(context.Context, *WriteSchemaRequest) (*WriteSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteSchema not implemented")
}
func (UnimplementedLamplightServiceServer) ReadSchema(context.Context, *ReadSchemaRequest) (*ReadSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSchema not implemented")
}
func (UnimplementedLamplightServiceServer) ListSchemaSets(context.Context, *ListSchemaSetsRequest) (*ListSchemaSetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemaSets not implemented")
}
func (UnimplementedLamplightServiceServer) DeleteSchemaSet(context.Context, *DeleteSchemaSetRequest) (*DeleteSchemaSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSchemaSet not implemented")
}
func (UnimplementedLamplightServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLamplightServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedLamplightServiceServer) EnsurePath(context.Context, *EnsurePathRequest) (*EnsurePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsurePath not implemented")
}
func (UnimplementedLamplightServiceServer) CheckPath(context.Context, *CheckPathRequest) (*CheckPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPath not implemented")
}
func (UnimplementedLamplightServiceServer) GrantRole(context.Context, *GrantRoleRequest) (*GrantRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantRole not implemented")
}
func (UnimplementedLamplightServiceServer) RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeRole not implemented")
}
func (UnimplementedLamplightServiceServer) ListRoleAssignments(context.Context, *ListRoleAssignmentsRequest) (*ListRoleAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoleAssignments not implemented")
}
func (UnimplementedLamplightServiceServer) ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedLamplightServiceServer) mustEmbedUnimplementedLamplightServiceServer() {}
func (UnimplementedLamplightServiceServer) testEmbeddedByValue()                          {}

// UnsafeLamplightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LamplightServiceServer will
// result in compilation errors.
type UnsafeLamplightServiceServer interface {
	mustEmbedUnimplementedLamplightServiceServer()
}

func RegisterLamplightServiceServer(s grpc.ServiceRegistrar, srv LamplightServiceServer) {
	// If the following call panics, it indicates UnimplementedLamplightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LamplightService_ServiceDesc, srv)
}

func _LamplightService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_Expand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).Expand(ctx, req.(*ExpandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_WriteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).WriteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_WriteSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).WriteSchema(ctx, req.(*WriteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_ReadSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).ReadSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_ReadSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).ReadSchema(ctx, req.(*ReadSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_ListSchemaSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemaSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).ListSchemaSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_ListSchemaSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).ListSchemaSets(ctx, req.(*ListSchemaSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_DeleteSchemaSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).DeleteSchemaSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_DeleteSchemaSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).DeleteSchemaSet(ctx, req.(*DeleteSchemaSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_EnsurePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsurePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).EnsurePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_EnsurePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).EnsurePath(ctx, req.(*EnsurePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_CheckPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).CheckPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_CheckPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).CheckPath(ctx, req.(*CheckPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_GrantRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).GrantRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_GrantRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).GrantRole(ctx, req.(*GrantRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).RevokeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_RevokeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).RevokeRole(ctx, req.(*RevokeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_ListRoleAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).ListRoleAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_ListRoleAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).ListRoleAssignments(ctx, req.(*ListRoleAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LamplightService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamplightServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamplightService_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamplightServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LamplightService_ServiceDesc is the grpc.ServiceDesc for LamplightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LamplightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carabiner.ll.v1.LamplightService",
	HandlerType: (*LamplightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _LamplightService_Check_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _LamplightService_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _LamplightService_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _LamplightService_Delete_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _LamplightService_ListObjects_Handler,
		},
		{
			MethodName: "Expand",
			Handler:    _LamplightService_Expand_Handler,
		},
		{
			MethodName: "WriteSchema",
			Handler:    _LamplightService_WriteSchema_Handler,
		},
		{
			MethodName: "ReadSchema",
			Handler:    _LamplightService_ReadSchema_Handler,
		},
		{
			MethodName: "ListSchemaSets",
			Handler:    _LamplightService_ListSchemaSets_Handler,
		},
		{
			MethodName: "DeleteSchemaSet",
			Handler:    _LamplightService_DeleteSchemaSet_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _LamplightService_HealthCheck_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _LamplightService_WhoAmI_Handler,
		},
		{
			MethodName: "EnsurePath",
			Handler:    _LamplightService_EnsurePath_Handler,
		},
		{
			MethodName: "CheckPath",
			Handler:    _LamplightService_CheckPath_Handler,
		},
		{
			MethodName: "GrantRole",
			Handler:    _LamplightService_GrantRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _LamplightService_RevokeRole_Handler,
		},
		{
			MethodName: "ListRoleAssignments",
			Handler:    _LamplightService_ListRoleAssignments_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _LamplightService_ListRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "carabiner/ll/v1/service.proto",
}
