// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/ll/v1/types.proto

package llv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelationTuple implements the zanzibar tuple, it represents a relationship
// between an object and a subject.
//
// Format: object_type:object_id#relation@subject_type:subject_id[#subject_relation]
type RelationTuple struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ObjectType  string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId    string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation    string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectType string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId   string                 `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// Optional: for subject sets (e.g., group:eng#member)
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelationTuple) Reset() {
	*x = RelationTuple{}
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTuple) ProtoMessage() {}

func (x *RelationTuple) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTuple.ProtoReflect.Descriptor instead.
func (*RelationTuple) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *RelationTuple) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *RelationTuple) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RelationTuple) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationTuple) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *RelationTuple) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *RelationTuple) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

// ConsistencyToken is an opaque token representing a point-in-time snapshot.
type ConsistencyToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyToken) Reset() {
	*x = ConsistencyToken{}
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyToken) ProtoMessage() {}

func (x *ConsistencyToken) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyToken.ProtoReflect.Descriptor instead.
func (*ConsistencyToken) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *ConsistencyToken) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// Consistency specifies the consistency requirements for a read operation.
type Consistency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Requirement:
	//
	//	*Consistency_MinimizeLatency
	//	*Consistency_FullyConsistent
	//	*Consistency_AtLeastAsFresh
	Requirement   isConsistency_Requirement `protobuf_oneof:"requirement"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consistency) Reset() {
	*x = Consistency{}
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consistency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consistency) ProtoMessage() {}

func (x *Consistency) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consistency.ProtoReflect.Descriptor instead.
func (*Consistency) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Consistency) GetRequirement() isConsistency_Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *Consistency) GetMinimizeLatency() bool {
	if x != nil {
		if x, ok := x.Requirement.(*Consistency_MinimizeLatency); ok {
			return x.MinimizeLatency
		}
	}
	return false
}

func (x *Consistency) GetFullyConsistent() bool {
	if x != nil {
		if x, ok := x.Requirement.(*Consistency_FullyConsistent); ok {
			return x.FullyConsistent
		}
	}
	return false
}

func (x *Consistency) GetAtLeastAsFresh() *ConsistencyToken {
	if x != nil {
		if x, ok := x.Requirement.(*Consistency_AtLeastAsFresh); ok {
			return x.AtLeastAsFresh
		}
	}
	return nil
}

type isConsistency_Requirement interface {
	isConsistency_Requirement()
}

type Consistency_MinimizeLatency struct {
	// Minimize latency; may return slightly stale data.
	MinimizeLatency bool `protobuf:"varint,1,opt,name=minimize_latency,json=minimizeLatency,proto3,oneof"`
}

type Consistency_FullyConsistent struct {
	// Fully consistent; reads reflect all prior writes.
	FullyConsistent bool `protobuf:"varint,2,opt,name=fully_consistent,json=fullyConsistent,proto3,oneof"`
}

type Consistency_AtLeastAsFresh struct {
	// At least as fresh as the given token.
	AtLeastAsFresh *ConsistencyToken `protobuf:"bytes,3,opt,name=at_least_as_fresh,json=atLeastAsFresh,proto3,oneof"`
}

func (*Consistency_MinimizeLatency) isConsistency_Requirement() {}

func (*Consistency_FullyConsistent) isConsistency_Requirement() {}

func (*Consistency_AtLeastAsFresh) isConsistency_Requirement() {}

// RelationTupleFilter is used to filter tuples in read/delete operations.
type RelationTupleFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectFilter *SubjectFilter         `protobuf:"bytes,4,opt,name=subject_filter,json=subjectFilter,proto3" json:"subject_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationTupleFilter) Reset() {
	*x = RelationTupleFilter{}
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationTupleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTupleFilter) ProtoMessage() {}

func (x *RelationTupleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTupleFilter.ProtoReflect.Descriptor instead.
func (*RelationTupleFilter) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *RelationTupleFilter) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *RelationTupleFilter) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RelationTupleFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationTupleFilter) GetSubjectFilter() *SubjectFilter {
	if x != nil {
		return x.SubjectFilter
	}
	return nil
}

// SubjectFilter filters by subject fields.
type SubjectFilter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SubjectType     string                 `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectRelation string                 `protobuf:"bytes,3,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubjectFilter) Reset() {
	*x = SubjectFilter{}
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectFilter) ProtoMessage() {}

func (x *SubjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_ll_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectFilter.ProtoReflect.Descriptor instead.
func (*SubjectFilter) Descriptor() ([]byte, []int) {
	return file_carabiner_ll_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *SubjectFilter) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SubjectFilter) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SubjectFilter) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

var File_carabiner_ll_v1_types_proto protoreflect.FileDescriptor

const file_carabiner_ll_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1bcarabiner/ll/v1/types.proto\x12\x0fcarabiner.ll.v1\"\xd6\x01\n" +
	"\rRelationTuple\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\x12)\n" +
	"\x10subject_relation\x18\x06 \x01(\tR\x0fsubjectRelation\"(\n" +
	"\x10ConsistencyToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"\xc6\x01\n" +
	"\vConsistency\x12+\n" +
	"\x10minimize_latency\x18\x01 \x01(\bH\x00R\x0fminimizeLatency\x12+\n" +
	"\x10fully_consistent\x18\x02 \x01(\bH\x00R\x0ffullyConsistent\x12N\n" +
	"\x11at_least_as_fresh\x18\x03 \x01(\v2!.carabiner.ll.v1.ConsistencyTokenH\x00R\x0eatLeastAsFreshB\r\n" +
	"\vrequirement\"\xb6\x01\n" +
	"\x13RelationTupleFilter\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12E\n" +
	"\x0esubject_filter\x18\x04 \x01(\v2\x1e.carabiner.ll.v1.SubjectFilterR\rsubjectFilter\"|\n" +
	"\rSubjectFilter\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12)\n" +
	"\x10subject_relation\x18\x03 \x01(\tR\x0fsubjectRelationB6Z4github.com/carabiner-dev/ll/api/carabiner/ll/v1;llv1b\x06proto3"

var (
	file_carabiner_ll_v1_types_proto_rawDescOnce sync.Once
	file_carabiner_ll_v1_types_proto_rawDescData []byte
)

func file_carabiner_ll_v1_types_proto_rawDescGZIP() []byte {
	file_carabiner_ll_v1_types_proto_rawDescOnce.Do(func() {
		file_carabiner_ll_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_ll_v1_types_proto_rawDesc), len(file_carabiner_ll_v1_types_proto_rawDesc)))
	})
	return file_carabiner_ll_v1_types_proto_rawDescData
}

var file_carabiner_ll_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_carabiner_ll_v1_types_proto_goTypes = []any{
	(*RelationTuple)(nil),       // 0: carabiner.ll.v1.RelationTuple
	(*ConsistencyToken)(nil),    // 1: carabiner.ll.v1.ConsistencyToken
	(*Consistency)(nil),         // 2: carabiner.ll.v1.Consistency
	(*RelationTupleFilter)(nil), // 3: carabiner.ll.v1.RelationTupleFilter
	(*SubjectFilter)(nil),       // 4: carabiner.ll.v1.SubjectFilter
}
var file_carabiner_ll_v1_types_proto_depIdxs = []int32{
	1, // 0: carabiner.ll.v1.Consistency.at_least_as_fresh:type_name -> carabiner.ll.v1.ConsistencyToken
	4, // 1: carabiner.ll.v1.RelationTupleFilter.subject_filter:type_name -> carabiner.ll.v1.SubjectFilter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_carabiner_ll_v1_types_proto_init() }
func file_carabiner_ll_v1_types_proto_init() {
	if File_carabiner_ll_v1_types_proto != nil {
		return
	}
	file_carabiner_ll_v1_types_proto_msgTypes[2].OneofWrappers = []any{
		(*Consistency_MinimizeLatency)(nil),
		(*Consistency_FullyConsistent)(nil),
		(*Consistency_AtLeastAsFresh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_ll_v1_types_proto_rawDesc), len(file_carabiner_ll_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_ll_v1_types_proto_goTypes,
		DependencyIndexes: file_carabiner_ll_v1_types_proto_depIdxs,
		MessageInfos:      file_carabiner_ll_v1_types_proto_msgTypes,
	}.Build()
	File_carabiner_ll_v1_types_proto = out.File
	file_carabiner_ll_v1_types_proto_goTypes = nil
	file_carabiner_ll_v1_types_proto_depIdxs = nil
}
